# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [58]:
import numpy as np;

2. Create a null vector of size 10 

In [4]:
vn = np.zeros(10)

3. Create a vector with values ranging from 10 to 49

In [5]:
vr = np.arange(10,50)

4. Find the shape of previous array in question 3

In [6]:
np.shape(vr)

(40,)

5. Print the type of the previous array in question 3

In [7]:
vr.dtype

dtype('int64')

6. Print the numpy version and the configuration


In [8]:
print(np.__version__)
print(np.show_config())

1.19.2
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/anaconda3/include']
None


7. Print the dimension of the array in question 3


In [9]:
vr.ndim

1

8. Create a boolean array with all the True values

In [10]:
ba = np.ones((4), dtype='bool')

9. Create a two dimensional array




In [11]:
array2D = np.arange(10).reshape(2,5)

10. Create a three dimensional array



In [11]:
array3D = np.arange(8).reshape(2,2,2)

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [13]:
np.flip(np.arange(5))

array([4, 3, 2, 1, 0])

12. Create a null vector of size 10 but the fifth value which is 1 

In [14]:
nVec = np.zeros(10, dtype=int)
nVec[4]=1

13. Create a 3x3 identity matrix

In [16]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [19]:
arr.astype(float)

array([1., 2., 3., 4., 5.])

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [21]:
np.multiply(arr1,arr2)

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [25]:
comparisonArray = (arr1==arr2.all())
comparisonArray

array([[False, False, False],
       [False, False, False]])

17. Extract all odd numbers from arr with values(0-9)

In [31]:
arr = np.arange(10)
arr[(arr%2 != 0)]

array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [32]:
arr = np.arange(10)
arr[(arr%2 != 0)] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [36]:
arr = np.arange(10)
arr[[5,6,7,8]] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [37]:
a = np.zeros((6,6), dtype=int)
a[:,[0,-1]] = 1
a[[0,-1]] = 1
a

array([[1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [39]:
arr2d[1][1] = 12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [41]:
arr3d[0,0] = 64
arr3d

array([[[64, 64, 64],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [45]:
q23= np.arange(10).reshape(2,5)
q23[0:1,0:]

array([[0, 1, 2, 3, 4]])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [48]:
q24= np.arange(10).reshape(2,5)
q24[1:,1:2]

array([[6]])

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [54]:
q25= np.arange(10).reshape(2,5)
q25
q25[0:2,2:3]

array([[2],
       [7]])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [65]:
q26 = np.random.randn(10,10)
np.min(q26),np.max(q26)

(-2.1574126434334415, 2.441060914364487)

# 27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [72]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [74]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)

(array([1, 3, 5, 7]),)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [78]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
print(data)
data[np.where(names != 'Will')]

[[-0.67320423  1.48335007 -0.61370923  1.19949649]
 [-1.31444316 -0.97679577 -0.54084808 -0.82951535]
 [ 0.97500186  0.17665763 -0.28566135 -1.39088749]
 [-0.34298222 -0.4104196   0.38427035  0.76885014]
 [ 0.06962497  1.04052417 -0.3551524   0.28717489]
 [ 1.66189366 -0.37255872 -0.78559096  0.61438756]
 [-0.19377292 -0.4810736  -0.43021962 -0.87038951]]


array([[-0.67320423,  1.48335007, -0.61370923,  1.19949649],
       [-1.31444316, -0.97679577, -0.54084808, -0.82951535],
       [-0.34298222, -0.4104196 ,  0.38427035,  0.76885014],
       [ 1.66189366, -0.37255872, -0.78559096,  0.61438756],
       [-0.19377292, -0.4810736 , -0.43021962, -0.87038951]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [88]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
data[np.where((names != 'Will') & (names != 'Joe'))]

array([[ 0.92311942,  1.30124433,  2.11423061,  0.76719942],
       [ 0.50223058,  0.5883792 , -1.25731688,  1.44438069]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [95]:
np.random.uniform(low=1, high=15, size=(5,3))

array([[13.24220885,  9.74080605, 13.46001407],
       [ 9.46384492, 10.18637246, 11.35879894],
       [ 4.22953882,  3.16330552,  7.16462746],
       [13.21413275,  6.77583424, 13.8316752 ],
       [ 5.10615604,  4.08052523,  6.2392301 ]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [97]:
q32=np.random.uniform(low=1, high=16, size=(2,2,4))
q32

array([[[ 9.21140339,  2.23818151,  7.25725183, 12.22647285],
        [14.94955262, 12.31808607, 14.76917001, 14.81460121]],

       [[ 4.37494793, 15.74664685,  5.87144395,  2.17995112],
        [12.518444  ,  1.39367117, 13.03844916, 10.74230573]]])

33. Swap axes of the array you created in Question 32

In [101]:
np.swapaxes(q32,0,-1)

array([[[ 9.21140339,  4.37494793],
        [14.94955262, 12.518444  ]],

       [[ 2.23818151, 15.74664685],
        [12.31808607,  1.39367117]],

       [[ 7.25725183,  5.87144395],
        [14.76917001, 13.03844916]],

       [[12.22647285,  2.17995112],
        [14.81460121, 10.74230573]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [126]:
sr = np.sqrt(np.arange(10))
np.where(sr<0.5,0,sr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [136]:
a = np.random.randn(12)
print('First Array:\n')
print(a)
b = np.random.randn(12)
print('Second Array:\n')
print(b)
print("Array of max values:")
np.where(a > b, a, b)


First Array:

[-0.38871097 -0.16253737  0.08212992  1.45931067  0.95942914 -0.58525221
 -0.84826723  2.16735122 -1.72318171 -0.00444051 -1.58592227  1.34308443]
Second Array:

[ 1.29386367  0.98358945 -1.61784328 -0.82709414 -1.98178956 -0.01574206
 -1.52710411 -0.96836422 -0.30612472  1.24749164 -0.16414499 -0.17731894]
Array of max values:


array([ 1.29386367,  0.98358945,  0.08212992,  1.45931067,  0.95942914,
       -0.01574206, -0.84826723,  2.16735122, -0.30612472,  1.24749164,
       -0.16414499,  1.34308443])

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [146]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.sort(np.unique(names))

array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [164]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
np.delete(a,np.where(a==b))

array([1, 2, 3, 4, 5])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [178]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])
sampleArray[:,1:2] = newColumn.T
sampleArray

array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [179]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
np.dot(x,y)



array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [184]:
np.random.randn(20).sum()

4.104961687852369